abstract: Fix double encoded UTF-8 bytes to the correct one
author: Tatsuhiko Miyagawa <miyagawa@bulknews.net>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Encode-DoubleEncodedUTF8
no_index: 
  directory: 
    - inc
    - t
requires: 
  Encode: 0.12
version: 0.01
