---
abstract: 'Fix double encoded UTF-8 bytes to the correct one'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Encode-DoubleEncodedUTF8
no_index:
  directory:
    - inc
    - t
requires:
  Encode: 0.12
  Filter::Util::Call: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.04
